//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateBL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Skills
    {
        public long ID { get; set; }
        public Nullable<long> CandidateID { get; set; }
        public Nullable<long> SkillID { get; set; }
    }
}
