//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandidateBL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public long ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public Nullable<int> Years_of_Experience { get; set; }
        public string PreviousEmployer { get; set; }
        public string CurrentEmployer { get; set; }
    }
}
